name: Publish a docker image to artifact registry
description: Publish Dex image to artifact registry

inputs:
  image-name:
    required: True
    description: The name of the image to publish
  service-account:
    required: true
    description: Service account for google artifact registry
  repo-name:
    required: true
    description: Artifact registry repo name
  docker-file:
    required: true
    description: Docker file path
  image-tag:
    required: false
    description: Additional tag for the image

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Default to provided sha
      run: echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      shell: bash

    - name: Build image
      run: |
        docker build -t ${{ inputs.image-name }} -f ${{ inputs.docker-file }} .
      shell: bash

    - uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ inputs.service-account }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"

    - name: "Docker auth"
      shell: bash
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Tag and Publish Docker image
      run: |
        docker tag ${{ inputs.image-name }} us-central1-docker.pkg.dev/athelas-rcm/${{ inputs.repo-name }}/${{ inputs.image-name }}:$GIT_SHA
        docker push us-central1-docker.pkg.dev/athelas-rcm/${{ inputs.repo-name }}/${{ inputs.image-name }}:$GIT_SHA
      shell: bash

    - name: Add additional tag if provided
      if: ${{ inputs.image-tag }}
      run: |
        docker tag ${{ inputs.image-name }} us-central1-docker.pkg.dev/athelas-rcm/${{ inputs.repo-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        docker push us-central1-docker.pkg.dev/athelas-rcm/${{ inputs.repo-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
